package com.robby.entity;
// Generated Nov 1, 2017 11:09:10 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "oopl20171")
public class Department implements java.io.Serializable {

    private Integer id;
    private String code;
    private String name;
    private boolean status;
    private Date created;
    private Set<Student> students = new HashSet<Student>(0);

    public Department() {
    }

    public Department(String code, String name, boolean status, Date created) {
        this.code = code;
        this.name = name;
        this.status = status;
        this.created = created;
    }

    public Department(String code, String name, boolean status, Date created, Set<Student> students) {
        this.code = code;
        this.name = name;
        this.status = status;
        this.created = created;
        this.students = students;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "code", nullable = false, length = 3)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "status", nullable = true)
    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = true, length = 19)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
    public Set<Student> getStudents() {
        return this.students;
    }

    public void setStudents(Set<Student> students) {
        this.students = students;
    }

}
